# Generated by Django 3.0.6 on 2020-11-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location1', models.CharField(max_length=200)),
                ('location2', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('severity', models.CharField(max_length=200)),
                ('cause', models.CharField(max_length=200)),
                ('actions', models.CharField(max_length=200)),
                ('type_env', models.BooleanField(default=False)),
                ('type_inju', models.BooleanField(default=False)),
                ('type_property', models.BooleanField(default=False)),
                ('type_vehicle', models.BooleanField(default=False)),
            ],
        ),
    ]
