# Generated by Django 3.0.6 on 2020-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='type_env',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_inju',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_property',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_vehicle',
            field=models.CharField(max_length=200),
        ),
    ]
