# Generated by Django 3.0.6 on 2020-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_auto_20201119_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='type_env',
            field=models.CharField(blank=True, default='f', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_inju',
            field=models.CharField(blank=True, default='f', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_property',
            field=models.CharField(blank=True, default='f', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_vehicle',
            field=models.CharField(blank=True, default='f', max_length=200, null=True),
        ),
    ]
