# Generated by Django 3.0.6 on 2020-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0005_auto_20201119_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='type_env',
            field=models.CharField(default='f', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_inju',
            field=models.CharField(default='f', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_property',
            field=models.CharField(default='f', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='type_vehicle',
            field=models.CharField(default='f', editable=False, max_length=200),
        ),
    ]
